apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: chert
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app: my-mysql12-exporter
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - default