apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-clusterrb
subjects:
- kind: ServiceAccount
  name: mysql-operator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: mysql-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io