apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator-sa
      containers:
      - name: mysql-operator
        image: registry.hamdocker.ir/shamim/mysql-operator:1.9
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      
      imagePullSecrets:
      - name: my-registry-secret