apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "configmaps", "events"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "create", "delete", "update", "watch"]
- apiGroups: ["dbaas.shamim.dev"]
  resources: ["mysqls", "mysqls/status"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["operator.victoriametrics.com"]
  resources: ["vmservicescrapes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]